version: '2'
services:
  mtail:
    build: mtail
    command:
      - "-progs"
      - "/etc/mtail"
      - "-logs"
      - "/var/log/chia/debug.log"
      - "-logtostderr"
    volumes:
      - c:/Users/toman/.chia/mainnet/log/:/var/log/chia/
  chia_exporter:
    build: chia_exporter
    command:
      - "-cert"
      - "/etc/chia.crt"
      - "-key"
      - "/etc/chia.key"
      - "-url"
      - "https://host.docker.internal:8555"
      - "-wallet"
      - "https://host.docker.internal:9256"
    volumes:
      - c:/Users/toman/.chia/mainnet/config/ssl/full_node/private_full_node.crt:/etc/chia.crt
      - c:/Users/toman/.chia/mainnet/config/ssl/full_node/private_full_node.key:/etc/chia.key
  prometheus:
    build: prometheus
    volumes:
      - prom_data:/prometheus
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:2.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    build: promtail
    volumes:
      - c:/Users/toman/.chia/mainnet/log:/var/log/chia
      - c:/Users/toman/.chia/mainnet/plotter:/var/log/plotter
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
  grafana:
    build: grafana
    ports:
      - "3000:3000"
volumes:
  prom_data:
